# Generated by Django 5.1.4 on 2024-12-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
