# Generated by Django 5.1.4 on 2024-12-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successapp', '0003_alter_comment_options_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
